### ISSUE TITLE
Replace buildpack.yml examples with environment variables

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/samples#101]
## What happened?
There are several sample apps in this repo that still reference the `buildpack.yml` format for configuration. We should update all of these apps to use environment variables either through the addition of a `project.toml` or updating the `pack build` commands in the README to explicitly set this environment variable.

**Comment by ForestEckhardt** [comment]
Partially completed in #229. However there are still some PHP samples that will need to be shifted once the buildpack is accepting environment variable configuartion.

**Comment by fg-j** [comment]
Blocked on https://github.com/paketo-buildpacks/php/issues/485, which will move PHP from using `buildpack.yml` to environment variables.

**Comment by fg-j** [comment]
There are no longer buildpack.yml examples.
