### ISSUE TITLE
Running "Getting Started" gives node dependancy error

### ISSUE THREAD

**Issue by thehandsomezebra** [paketo-buildpacks/samples#124]
## What happened?

* What were you attempting to do?
Perform the "Getting Started" steps

* What did you expect to happen?
No errors, sample app built

* What was the actual behavior? Please provide log output, if possible.
```
Paketo CA Certificates Buildpack 2.2.0
  https://github.com/paketo-buildpacks/ca-certificates
  Launch Helper: Contributing to layer
    Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
Paketo Node Engine Buildpack 0.4.0
  Resolving Node Engine version
    Candidate version sources (in priority order):
      package.json -> "~10"
      <unknown>    -> ""

failed to satisfy "node" dependency version constraint "~10": no compatible versions. Supported versions are: [12.22.0, 12.22.1, 14.16.1, 14.17.0, 15.13.0, 15.14.0, 16.1.0, 16.2.0]
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

## Build Configuration
* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.
Fresh install of pack using `brew install buildpacks/tap/pack`
```
➜  ~ pack --version
0.19.0+git-360dbae.build-2550
```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

Performed steps noted here:
https://paketo.io/docs/

## Checklist

* [X] I have included log output.
* [X] The log output includes an error message.
* [X] I have included steps for reproduction.

**Comment by arjun024** [comment]
Hi @thehandsomezebra, thanks for reporting.  Yes support for version 10 was removed as it went out of support (https://nodejs.org/en/about/releases/) and the demo app wasn't updated. Thanks for the PR

**Comment by simpleprogrammer2** [comment]
I got pack command not found ?? Am I missing something ?
