### ISSUE TITLE
Unable to run example from documentation, GCR auth

### ISSUE THREAD

**Issue by qayshp** [paketo-buildpacks/samples#146]
## What happened?

`gcr.io` wouldn't let me download the image needed

* What were you attempting to do?
  * Use the sample, as described and copy/pasta'd from [docs](https://paketo.io/docs/howto/dotnet-core/#build-a-sample-app)

```
git clone https://github.com/paketo-buildpacks/samples
cd samples/dotnet-core/aspnet
pack build my-app --buildpack gcr.io/paketo-buildpacks/dotnet-core \
  --builder paketobuildpacks/builder:base
```

* What did you expect to happen?
  * To be able to build the sample project.
* What was the actual behavior? Please provide log output, if possible.
  * `auth for ref gcr.io/paketo-buildpacks/dotnet-core` failed

```
git clone https://github.com/paketo-buildpacks/samples
cd samples/dotnet-core/aspnet
pack build my-app --buildpack gcr.io/paketo-buildpacks/dotnet-core \
  --builder paketobuildpacks/builder:base

Cloning into 'samples'...
remote: Enumerating objects: 1783, done.
remote: Counting objects: 100% (483/483), done.
remote: Compressing objects: 100% (242/242), done.
remote: Total 1783 (delta 345), reused 332 (delta 231), pack-reused 1300
Receiving objects: 100% (1783/1783), 22.78 MiB | 512.00 KiB/s, done.
Resolving deltas: 100% (971/971), done.
base: Pulling from paketobuildpacks/builder
Digest: sha256:8f82384b8c6ec0415c5b62df6fbc4f28e52154a6f084af851fa3a8b0fd726fba
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:3bdefd40188e93e4aba93978440816f9b86d03a1a7b58e6c6c854bcb88df8ace
Status: Image is up to date for paketobuildpacks/run:base-cnb
ERROR: failed to build: creating from buildpackage gcr.io/paketo-buildpacks/dotnet-core: fetching image: resolve auth for ref gcr.io/paketo-buildpacks/dotnet-core: error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: ``
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
  * `pack --version => 0.20.0+git-66a4f32.build-2668`
* What buildpacks are you using? Please include versions.
  * Sorry, I'm not sure. Whatever the sample would get?
* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
  * Huge output, I can post this to a gist if needed.
* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
  * Sorry, also not sure here. Just used the sample.

## Checklist

* [X] I have included log output.
* [X] The log output includes an error message.
* [X] I have included steps for reproduction.

## Other

I really hope I didn't miss some step in the docs, but please let me know if I did.

**Comment by qayshp** [comment]
Forgot to add, and not sure if it matters, but on macOS 10.15.6 (19G73) with pack installed via homebrew.

**Comment by qayshp** [comment]
(sorry, closed by accident)

**Comment by qayshp** [comment]
This is probably specific to either setup's like mine, or just mine. :(
Not sure where to take it though. Docker Desktop? Buildpacks pack CLI? Either way, not here.

**Comment by fg-j** [comment]
Hi @qayshp. Thanks for filing an issue. Are you able to `docker pull gcr.io/paketo-buildpacks/dotnet-core`? If not, this seems like a docker authentication issue. If yes, this might be a pack CLI issue. From Paketo's side, we're still publishing the buildpack to that GCR repo, and they are still public -- nothing's changed. Good luck!

**Comment by qayshp** [comment]
Thanks for helping out fg-j! Removing all *.gcr.io entries in my docker config fixed it.

I'm not sure what added the gcr/gcloud config, since I haven't explicitly used gcr or installed any cli utils for it. I did add, but never use, a cloud vscode extension at some point, so I'm going to try that again.

```
{
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "credHelpers" : {
    "us.gcr.io" : "gcloud",
    "asia.gcr.io" : "gcloud",
    "marketplace.gcr.io" : "gcloud",
    "eu.gcr.io" : "gcloud",
    "staging-k8s.gcr.io" : "gcloud",
    "gcr.io" : "gcloud"
  },
  "credsStore" : "desktop",
  "experimental" : "disabled"
}
```
