### ISSUE TITLE
Node.js samples should not reference "main" in package.json

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/samples#17]
The "main" field in the `package.json` file is used to indicate an entrypoint for a node module. This only applies to library code and is not meant to indicate the entrypoint of an application. Furthermore, the Node.js language family does not have any mechanism to choose a start command using the "main" field if it did indicate the application's entrypoint.

The current Node.js sample applications include this key:

https://github.com/paketo-buildpacks/samples/blob/7d3ea572be7619632b1cf2db1cdd805389fee037/nodejs/npm/package.json#L8
https://github.com/paketo-buildpacks/samples/blob/7d3ea572be7619632b1cf2db1cdd805389fee037/nodejs/yarn/package.json#L8

It is confusing to users that this "main" field appears in the `package.json`, as it may lead some users to believe they can control the start command by changing this value.

These values should be removed from all Node.js sample applications so that this possible confusion is avoided.

[Slack Conversation](https://paketobuildpacks.slack.com/archives/CUD6R3CPL/p1602776261010300)

**Comment by ForestEckhardt** [comment]
This should also be done for all of the `testdata` apps in the Node.Js Buildpack Family.
