### ISSUE TITLE
Procfile sample seems broken

### ISSUE THREAD

**Issue by mattmoor** [paketo-buildpacks/samples#20]
When I build and deploy the Procfile sample, I get the error:
```
$ kubectl logs procfile-bdcxb-1-deployment-79657fc75f-nf9vb user-container
FOLDER=web: FOLDER=web: command not found
```

I believe this likely comes from here:
https://github.com/paketo-buildpacks/samples/blob/d82d47030176a74507c12821820b69b74635bd82/procfile/Procfile#L1

It sort of seems like the sample it treating the first argument as the binary executable instead of an environment variable to pass to the binary executable (as a shell might).

**Comment by mattmoor** [comment]
If I remove `FOLDER=web` and pass it at runtime, things seem to work fine.

**Comment by mattmoor** [comment]
No expert, but it seems like the issue is here:
https://github.com/paketo-buildpacks/procfile/blob/a4d84817dac21d16bbd563a63fb1517d7d8cb9f0/procfile/build.go#L46-L55

It parses the value with "shellwords" and passes the first as the command and the rest as arguments.

**Comment by nebhale** [comment]
@mattmoor Yep, a recent change to the `Procfile` buildpack that didn’t take this behavior into account.  @ekcasey this seems like more evidence for a move back to the “command string” behavior.  What’s your take?

**Comment by nebhale** [comment]
@mattmoor Resolved with https://github.com/paketo-buildpacks/procfile/pull/21.  Give it a bit of time to propagate out to the builders (Procfile Buildpack 3.0.0) and you'll be set.
