### ISSUE TITLE
Assert that sample apps work with the latest builders

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/samples#47]
## What happened?
* What were you attempting to do?
I was trying to confirm that the set of samples provided in this repo can be built with the current builders.

* What did you expect to happen?
I expected that there would be a set of tests that I could run to confirm this.

* What was the actual behavior? Please provide log output, if possible.
There are no tests, and so I need to try to confirm this in an ad-hoc manner.

## Checklist
* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by sophiewigmore** [comment]
Testing ca-certificates will be done in issue #70.
