### ISSUE TITLE
Angular example

### ISSUE THREAD

**Issue by emmanuelU17** [paketo-buildpacks/samples#591]
## Describe the Enhancement
Hi, all could you provide a sample project for angular developers? E.g. `ng build --configuration production`

## Possible Solution
Add some samples to build angular apps in different build mode. e.g. production, development, staging

## Motivation
Very hard to get this to work considering the example is only for React apps

**Comment by arjun024** [comment]
This (https://github.com/paketo-buildpacks/samples/pull/588) adds the use case of Angular (to build static assets) + NGINX to serve them, which I believe is the common production scenario. (use case of Paketo Web Servers Buildpack)

There's also angular app that runs a dev server here https://github.com/paketo-buildpacks/samples/tree/main/nodejs/angular-npm.

Does either meet your expectations?

**Comment by emmanuelU17** [comment]
Thank you. This was what I was looking for.
