### ISSUE TITLE
Add Sample apps for all configurations supported by .NET Core buildpack

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/samples#67]
## What happened?
The re-architected .NET Core buildpack supports builds of the following configurations:
- source-based
- self-contained
- framework-dependent deployment/executable

We currently just have sample apps for source-based ASP.NET and runtime apps; Could we look into adding some simple apps for all supported configurations?

**Comment by joshuatcasey** [comment]
I'd like to look into this, but will probably be no earlier than 2022-02-22, so if someone else wants to pick it up, please do so!

**Comment by joshuatcasey** [comment]
Picking it up now
