### ISSUE TITLE
Add a smoke test for ca-certificates sample app

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/samples#70]
## What happened?

Issue #47 is to implement tests for all of the sample apps against our builders. The test case for the `ca-certificates` sample app is less straightforward than the other test cases.

After discussing with @ekcasey, this will involve the following:
* generating a CA cert
* generating a cert signed by the CA
* standing up some kind of server that uses the above cert (during manual testing a used the nginx docker image for this)
* passing the endpoint of the server to the buildpack (at both build and run time)

We are punting this work from the initial testing issue, and into its own chunk of work. We would like to have this tested eventually.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by fg-j** [comment]
This should be relatively straightforward. We've got integration tests that do a similar thing in [the Go buildpack](https://github.com/paketo-buildpacks/go/blob/9c10787476edd476834f06ac2528d8a41fc0b339/integration/build_test.go#L176)
